// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_w2ACIp9tbJcdruNGHqV_-wHgQHz42BA',
    appId: '1:598610989523:web:e7e2adeb1ae0f957b81f26',
    messagingSenderId: '598610989523',
    projectId: 'plataformafin-d7def',
    authDomain: 'plataformafin-d7def.firebaseapp.com',
    storageBucket: 'plataformafin-d7def.appspot.com',
    measurementId: 'G-2HPESHST0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU_RUIXJJrmP1tX1YnpmgGgQQ4Gh6ATGk',
    appId: '1:598610989523:android:2f25ee23fb587e75b81f26',
    messagingSenderId: '598610989523',
    projectId: 'plataformafin-d7def',
    storageBucket: 'plataformafin-d7def.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiDvkvhYcg3Qeb68RmO1XG8IdW_agVsTY',
    appId: '1:598610989523:ios:52e217fa78b58115b81f26',
    messagingSenderId: '598610989523',
    projectId: 'plataformafin-d7def',
    storageBucket: 'plataformafin-d7def.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiDvkvhYcg3Qeb68RmO1XG8IdW_agVsTY',
    appId: '1:598610989523:ios:52e217fa78b58115b81f26',
    messagingSenderId: '598610989523',
    projectId: 'plataformafin-d7def',
    storageBucket: 'plataformafin-d7def.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_w2ACIp9tbJcdruNGHqV_-wHgQHz42BA',
    appId: '1:598610989523:web:57423ab54359d52fb81f26',
    messagingSenderId: '598610989523',
    projectId: 'plataformafin-d7def',
    authDomain: 'plataformafin-d7def.firebaseapp.com',
    storageBucket: 'plataformafin-d7def.appspot.com',
    measurementId: 'G-MFD0P8Q1N5',
  );
}
